#!/bin/bash

# Redirect pacman to wf-pacman on non-containerized platforms.
case "$(uname -s)" in
	MINGW*)
		export PATH=`pwd`/tool/windows:$PATH
		;;
    Darwin*)
        export PATH="/opt/homebrew/opt/llvm@16/bin:$PATH"
        export CC="/opt/homebrew/opt/llvm@16/bin/clang"
        export CXX="$CC++"
        export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/llvm@16/lib -mmacosx-version-min=10.15"
        export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/llvm@16/include -mmacosx-version-min=10.15"
        ;;
	*)
		;;
esac

# Run pkgtool.
uv run python -m tool.main "$@"
